#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "PearlNerf".  #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

## Time (in seconds) between thrown pearls when in combat.
# Default: 10
pearlCooldownTime: 10

## Whether or not a player's health is decreased if they attempt to pearl while under the effect of the nerf.
# Default: true
damageOnPearl: true

## Amount to damage the player's health by, if damageOnPearl is enabled.
# Default: 1
pearlDamageAmount: 1

## Whether or not to use Humbug code to correct teleportation positioning.
# Default: true
useHumbugCorrection: true

## Pearl fire delay threshold (in milliseconds).
# Default: 10
fireDelay: 10

## If damageOnPearl is enabled, this controls whether or not it is only applied to assumed auto-clickers.
# Default: true
onlyDamageAutoClickers: true

## Number of auto clicked pearl detections required for a player to be labelled for auto-clicking.
# Default: 4
minimumAutoClickedPearlCount: 4

#======== CombatTag Settings ========#

## Whether or not the pearl nerf effect requires the player to be combat tagged.
# Note: This requires the CombatTag plugin. If it is not present, this feature will not be enabled.
# Default: true
useCombatTag: true

## Whether or not a player needs to be combat-tagged for a pearl nerf effect to be applied.
# Default: true
requireCombatTagForEffect: true

## Whether or not a player is combat-tagged upon pearl teleport.
# Default: true
tagOnPearl: true

#======== Advanced Settings ========#

## Whether or not to output debug information.
# Default: false
printDebugInfo: false
