-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "PearlNerf".  #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

## Whether or not enderman enderpearl drop limiting is enabled.
# Default: true
limitPearlDrops: true

## The chance of recieving a pearl (as a percentage of the vanilla rate), if limitPearlDrops is true.
# Note: must be a value from 0.00 - 1.00
# Default: 0.95
pearlDropRate: 0.95