#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#  Configuration file for "PearlNerf".  #
#  @author Nikita Pekin (Indivisible0)  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#


#======== Settings ==========#

## Time (in seconds) between thrown pearls when in combat
# Default: 10
pearlCooldownTime: 10
